export const en = {
  brand: "AgentSannyii",
  tagline: "Single-file AI utilities you can run anywhere",
  heroTitle: "Every tiny problem, solved with a single HTML file.",
  heroBody:
    "Turn daily friction into standalone HTML tools. Generate, download, and run offline or online without installing apps.",
  heroPrimary: "Request a new tool",
  heroSecondary: "Browse all utilities",
  stats: [
    "Offline-ready",
    "Single-file delivery",
    "Generated by AI",
    "Works in any browser",
  ],
  sectionTitle: "Explore single-HTML utilities",
  filters: ["All", "Image", "Video", "File", "Text", "Productivity"],
  footerNote: "Internationalization-ready · English-only for now",
};
